### ISSUE TITLE
feat: ✨ icon-only button

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#354] opened 2024-02-29 15:06 UTC
# Checklist (for the issue creator)

- [x] I have looked at the documentation site and was not able to find the required feature.
- [x] I have looked into the Figma boards and was not able to find the required feature.
- [ ] I would be willing to provide a PR for this feature.

# Story

As a user of the Synergy Design System, I would like to put a single button without any text into a button. The button should be a square.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Button is a square after an icon is placed into default slot as only child
- [ ] unittests
- [ ] story

**Comment by schilchSICKAG** [comment] 2024-03-25 06:42
Duplicate of #309

**Closed** 2024-03-25 06:43 UTC
Labels: duplicate, enhancement
