### ISSUE TITLE
feat: ✨ Question: How to Mark an Element as Invalid

### ISSUE THREAD

**Issue by fabian-paus** [synergy-design-system/synergy-design-system#574] opened 2024-08-05 07:22 UTC
# Checklist (for the issue creator)

- [ x ] I have looked at the documentation site and was not able to find the required feature.
- [ x ] I have looked into the Figma boards and was not able to find the required feature.
- [ ] I would be willing to provide a PR for this feature.

# Question

How do I mark an element (syn-input, syn-textarea, ...) as invalid?

I see that there is an example with an invalid component (https://synergy-design-system.github.io/?path=/story/components-syn-input--invalid&globals=viewport:defaultViewPort).
But the documentation does not say anything about how to mark a component as invalid. Should we just copy the attributes from the example?

# Story

We have input fields that require custom validation logic. For example, a group name needs to be unique. We do an HTTP request to determine this and want to mark the input field (or whatever element) as invalid.

# Acceptance criteria

- [ ] The documentation explains how to mark an element as invalid.

**Comment by kirchsuSICKAG** [comment] 2024-08-09 08:29
Hi Fabian. 

Under the hood we are using the standard html input elements `<input />` .  If you are using e.g. the `pattern`, `required`,`max`, `min`, … properties this will all result in a validation, when the user interacts with the input elements (like `<syn-input />`, `syn-checkbox`,…) and you don`t need to do anything else:

![Image](https://github.com/user-attachments/assets/9adf5658-3f26-4aa1-81a1-5771e8d5fb31)

This is also the reason why the `reportValidity` method is showing this popup. This is the browser internal popup for standard html elements [see](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/reportValidity).
![](image.png)
This popup will also be shown if you are using our input elements in a `<form />` because under the hood the `reportValidity` will be called for all input elements (ours and standard html input elements) if a form is submitted. But this popup can be suppressed if you cancel the `syn-invalid` event :
```html
<form>
  <syn-input pattern="abc"></syn-input>
  <syn-button type="submit">Submit</syn-button>
</form>

<script type="module">
  const form = document.querySelector('form');
  form.addEventListener('syn-invalid', event => {
     // Suppress the browser's constraint validation message
     event.preventDefault();
    }, 
    { capture: true } // you must use capture since syn-invalid doesn't bubble!
 );
</script>
```

But if you don’t use the `<form/>` element you can just use the `checkValidity` method, which does the same as the `reportValidity` but doesn’t show the popup. It only checks for validity. For all the methods, which are available have a look at the „Methods“ part of the[docs table](https://synergy-design-system.github.io/?path=/docs/components-syn-input--docs)
![](image%202.png)


As you already found out, you can set your own custom validation / error state by using the „syn-change“ or „syn-input“ event, do your checks if it is valid for your use case and then set the `setCustomValidity` method. 

I just played around a bit and it really feels strange, that you need to type something, click somewhere else to let the validation get done for the first time. But this is actually the standard html behaviour. This is the reason, why your `blur()`and again `focus` is working. 
I will take this and discuss it in the team, if in this case we really want to stick with the standard html input.

**Comment by fabian-paus** [comment] 2024-08-12 08:48
Thanks for the quick reply. If this is the intended behavior and the workaround the supported way to handle these dynamic invalidations, then this is fine from our side too. A dynamic invalidation example to document the intended behavior would be great in this case 👍

**Comment by klaarseSICKAG** [comment] 2024-08-15 09:39
duplicate of https://github.com/synergy-design-system/synergy-design-system/issues/412

**Closed by klaarseSICKAG** 2024-08-15 09:39 UTC
Labels: enhancement, component/change
